[package]
edition = "2024"
name = "shadertoy"
version = "0.1.0"

[dependencies]
bytemuck = "1.24.0"
pollster = "0.4.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
wgpu = "28.0.0"
winit = "0.30.12"
