[package]
name = "shadertoy"
edition = "2024"
version = "0.1.0"

[dependencies]
bytemuck = "1.24.0"
pollster = "0.4.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "tracing-log"] }
wgpu = "28.0.0"
winit = "0.30.12"
